name: Loverology™
favicon: null
layout_spectrum: 0.7492
typography_spectrum: 0.71993
title: Loverology™
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e68ab9'
    - '#ff0000'
    - '#aa55aa'
    - '#ff00ff'
  brandStrength: 0.3125
  lightness: 0.6660889219492674
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
