name: Loverology™
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71993
title: Loverology™
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f3c5dc'
    - '#fbecf4'
    - '#eca0c6'
    - '#e68ab9'
  brandStrength: 0.3125
  lightness: 0.6660889219492674
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
