name: Loverology
favicon: null
layout_spectrum: 0.5867165732197464
typography_spectrum: 0.0939648759085685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.16088052582927048
  lightness: 0.6660889219492674
  saturation: 0.26365874893963337
  rhythmicContrast: 0.9830723451450467
purpose: []
